using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace CSG
{
    public class Intersection
    {
        public Triangle triangle;// the triangle this intersection hits
        public Vertex vertex;// the vertex generated by this intersection
        public Edge edge;// the edge this intersection was generated by

        public Intersection(Triangle triangle, Vertex vertex, Edge edge)
        {
            this.triangle = triangle;
            this.vertex = vertex;
            this.edge = edge;
        }
    }
}

